# .gitlab-ci.yml
stages:
  - build_backend
  - build_frontend

build_backend:
  stage: build_backend
  image: composer:latest
  script:
    - cd backend
    - composer install
    - composer check

build_frontend:
  stage: build_frontend
  image: node:latest
  script:
    - cd frontend && npm install
    -  npm run build
    - npm run lint
  needs: ["build_backend"]
    # Trigger the pipeline on every push
push_trigger:
  stage: build_frontend
  script:
    - echo "Triggered by push"
  only:
    - merge_requests
    - master
    - branches

# Trigger the pipeline on every merge request
merge_request_trigger:
  stage: build_frontend
  script:
    - echo "Triggered by merge request"
  only:
    - merge_requests
    - master
    - branches
