# .gitlab-ci.yml

stages:
  - test_frontend
  - test_backend
  - build_frontend
  - build_backend

test_frontend:
  stage: test_frontend
  image: node:latest
  script:
    - cd frontend && npm install
    - npm run lint
  only:
    - branches
    - merge_requests
    - master
  needs: ["build_frontend"]

test_backend:
  stage: test_backend
  image: composer:latest
  script:
    - cd backend
    - composer install
    - composer check
  only:
    - branches
    - merge_requests
    - master
  needs: [ "build_backend" ]

build_frontend:
  stage: build_frontend
  image: node:latest
  script:
    - cd frontend && npm install
    - npm run build

build_backend:
  stage: build_backend
  image: composer:latest
  script:
    - cd backend
    - composer install