# .gitlab-ci.yml

stages:
  - push
  - merge_request

build_frontend:
  image: node:latest
  script:
    - cd frontend && npm install
    - npm run build

build_backend:
  image: composer:latest
  script:
    - cd backend
    - composer install

test_frontend:
  image: node:latest
  script:
    - cd frontend && npm install
    - npm run lint

test_backend:
  image: composer:latest
  script:
    - cd backend
    - composer install
    - composer check

# Trigger the pipeline on every push
push_trigger:
  stage: push
  script:
    - echo "Triggered by push"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  needs:
    - build_backend
    - test_backend
    - build_frontend
    - test_frontend

# Trigger the pipeline on every merge request
merge_request_trigger:
  stage: merge_request
  script:
    - echo "Triggered by merge request"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  needs:
    - build_backend
    - test_backend
    - build_frontend
    - test_frontend